import {
  alertPattern,
  alertdialogPattern,
  disclosurePattern,
  navigationListPattern,
  sliderPattern,
  windowsplitterPattern,
  toggleSwitchPattern,
  useAccordionPattern,
  useComboboxPattern,
  useDialogModalPattern,
  useListboxPattern,
  useMenuPattern,
  useMenubarPattern,
  useRadioPattern,
  useTabsPattern,
  useToolbarPattern,
  useTooltipPattern,
  useTreegridPattern,
  useTreeviewPattern,
} from './dist/patterns/index.js'
import { useRovingTabIndex, useSpatialNavigation, multiSelect, numericStep, selectionFollowsFocus } from './dist/index.js'
console.log('imports OK', {
  alertPattern: typeof alertPattern,
  alertdialogPattern: typeof alertdialogPattern,
  disclosurePattern: typeof disclosurePattern,
  navigationListPattern: typeof navigationListPattern,
  sliderPattern: typeof sliderPattern,
  windowsplitterPattern: typeof windowsplitterPattern,
  toggleSwitchPattern: typeof toggleSwitchPattern,
  useAccordionPattern: typeof useAccordionPattern,
  useComboboxPattern: typeof useComboboxPattern,
  useDialogModalPattern: typeof useDialogModalPattern,
  useListboxPattern: typeof useListboxPattern,
  useMenuPattern: typeof useMenuPattern,
  useMenubarPattern: typeof useMenubarPattern,
  useRadioPattern: typeof useRadioPattern,
  useTabsPattern: typeof useTabsPattern,
  useToolbarPattern: typeof useToolbarPattern,
  useTooltipPattern: typeof useTooltipPattern,
  useTreegridPattern: typeof useTreegridPattern,
  useTreeviewPattern: typeof useTreeviewPattern,
  multiSelect: typeof multiSelect,
  numericStep: typeof numericStep,
  selectionFollowsFocus: typeof selectionFollowsFocus,
  useRovingTabIndex: typeof useRovingTabIndex,
  useSpatialNavigation: typeof useSpatialNavigation,
})
